//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Loclization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Loclization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Field_Phone {
            get {
                return ResourceManager.GetString("Field_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        public static string Field_UserType_EndDate {
            get {
                return ResourceManager.GetString("Field_UserType_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        public static string Field_UserType_FileId {
            get {
                return ResourceManager.GetString("Field_UserType_FileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Field_UserType_Id {
            get {
                return ResourceManager.GetString("Field_UserType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة.
        /// </summary>
        public static string Field_UserType_ImageId {
            get {
                return ResourceManager.GetString("Field_UserType_ImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Field_UserType_IsActive {
            get {
                return ResourceManager.GetString("Field_UserType_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الأكبر.
        /// </summary>
        public static string Field_UserType_MaxDays {
            get {
                return ResourceManager.GetString("Field_UserType_MaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الأقل.
        /// </summary>
        public static string Field_UserType_MinDays {
            get {
                return ResourceManager.GetString("Field_UserType_MinDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم عربي.
        /// </summary>
        public static string Field_UserType_NameAr {
            get {
                return ResourceManager.GetString("Field_UserType_NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم إنجليزي.
        /// </summary>
        public static string Field_UserType_NameEn {
            get {
                return ResourceManager.GetString("Field_UserType_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string Field_UserType_StartDate {
            get {
                return ResourceManager.GetString("Field_UserType_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصحة.
        /// </summary>
        public static string WSO2Identity {
            get {
                return ResourceManager.GetString("WSO2Identity", resourceCulture);
            }
        }
    }
}
